// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=interfaces_mock.go -package=router -source=interfaces.go
//

// Package router is a generated GoMock package.
package router

import (
	context "context"
	reflect "reflect"

	domain "github.com/n-r-w/asteria/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockILSP is a mock of ILSP interface.
type MockILSP struct {
	ctrl     *gomock.Controller
	recorder *MockILSPMockRecorder
	isgomock struct{}
}

// MockILSPMockRecorder is the mock recorder for MockILSP.
type MockILSPMockRecorder struct {
	mock *MockILSP
}

// NewMockILSP creates a new mock instance.
func NewMockILSP(ctrl *gomock.Controller) *MockILSP {
	mock := &MockILSP{ctrl: ctrl}
	mock.recorder = &MockILSPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILSP) EXPECT() *MockILSPMockRecorder {
	return m.recorder
}

// Extensions mocks base method.
func (m *MockILSP) Extensions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extensions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Extensions indicates an expected call of Extensions.
func (mr *MockILSPMockRecorder) Extensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extensions", reflect.TypeOf((*MockILSP)(nil).Extensions))
}

// FindReferencingSymbols mocks base method.
func (m *MockILSP) FindReferencingSymbols(ctx context.Context, request *domain.FindReferencingSymbolsRequest) (domain.FindReferencingSymbolsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReferencingSymbols", ctx, request)
	ret0, _ := ret[0].(domain.FindReferencingSymbolsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReferencingSymbols indicates an expected call of FindReferencingSymbols.
func (mr *MockILSPMockRecorder) FindReferencingSymbols(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReferencingSymbols", reflect.TypeOf((*MockILSP)(nil).FindReferencingSymbols), ctx, request)
}

// FindSymbol mocks base method.
func (m *MockILSP) FindSymbol(ctx context.Context, request *domain.FindSymbolRequest) (domain.FindSymbolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSymbol", ctx, request)
	ret0, _ := ret[0].(domain.FindSymbolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSymbol indicates an expected call of FindSymbol.
func (mr *MockILSPMockRecorder) FindSymbol(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSymbol", reflect.TypeOf((*MockILSP)(nil).FindSymbol), ctx, request)
}

// GetSymbolsOverview mocks base method.
func (m *MockILSP) GetSymbolsOverview(ctx context.Context, request *domain.GetSymbolsOverviewRequest) (domain.GetSymbolsOverviewResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSymbolsOverview", ctx, request)
	ret0, _ := ret[0].(domain.GetSymbolsOverviewResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSymbolsOverview indicates an expected call of GetSymbolsOverview.
func (mr *MockILSPMockRecorder) GetSymbolsOverview(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSymbolsOverview", reflect.TypeOf((*MockILSP)(nil).GetSymbolsOverview), ctx, request)
}
